#development:
#  sync:
#    class: SyncStopsJob
#    args: [ 100 ]
#    schedule: every 5 minutes
production:
  sync_stops:
    class: SyncStopsJob
    args: [ 100 ]
    schedule: every 5 minutes
  generate_daily_reports:
    class: RouteDailyReports::GenerateReportsJob
    schedule: '0 0 * * *' # every day at 00:00
  delete_old_data:
    class: OldData::DeleteJob
    schedule: '0 0 * * *' # every day at 00:00
  sync_schedules:
    class: SyncSchedulesJob
    schedule: '0 0,8,23 * * *' # every day at 00:00, 08:00, 23:00

