#development:
#  sync:
#    class: SyncStopsJob
#    args: [ 100 ]
#    schedule: every 5 minutes
production:
  sync_stops:
    class: SyncStopsJob
    args: [ 100 ]
    schedule: every 5 minutes
  sync_schedules:
    class: SyncSchedulesJob
    schedule: every 1 day

